apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: carlos-teste
  region: us-east-1
  version: "1.23"
vpc:
  id: "vpc-03bba3dd9daf3cfe5"
  subnets:
    public:
      private-one:
        id: "subnet-0d05a7949d013fc45"
      private-two:
        id:  "subnet-0cffdb24d2020bfd0"
managedNodeGroups:
- name: carlos-nodegroup
  instanceType: t2.small
  minSize: 2
  maxSize: 4
  spot: true
  privateNetworking: true
  subnets:
    - private-one
    - private-two