apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: carlos-cluster
  region: us-east-1
  version: "1.23"
vpc:
  id: "vpc-03ff4222593a1c0a0"
  subnets:
    public:
      public-one:
        id: "subnet-0cfdd4c4b5e1c907f"
      public-two:
        id: "subnet-0c7bcadc551287a2a"
managedNodeGroups:
- name: carlos-nodegroup
  securityGroups:
    attachIDs: ["sg-024ab87aa99afcdb0"]
  instanceType: t3.medium
  minSize: 1
  maxSize: 4
  spot: true
  privateNetworking: false
  subnets:
    - public-one
    - public-two